[package]
name = "exo"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
anyhow = "1.0.95"
datafusion = "44.0.0"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
uuid = "1.11.0"
serde_json = "1.0.134"
#uuid = { }
